language: rust
rust:
  - stable

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo build --verbose --locked
  - cargo test --verbose --all

before_deploy:
  - cargo build --release

deploy:
  - provider: script
    script: cargo publish --token $CRATES_TOKEN
    skip_cleanup: true
    on:
        tags: true

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: target/release/gt
    skip_cleanup: true
    on:
        tags: true
