language: rust
rust:
  - stable

cache:
  cargo: true

before_cache:
  - find ./target -name "*goto_project-*" -exec rm -rf "{}" \;
  - find ./target -name "gt-*" -exec rm -rf "{}" \;
  - rm -rf ./target/.rustc_info.json
  - cargo clean -p goto-project

before_script:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview

script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo test --verbose --all

before_deploy:
  - cargo build --release

deploy:
  - provider: script
    script: cargo publish --token $CRATES_TOKEN
    skip_cleanup: true
    on:
        tags: true

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: target/release/gt
    skip_cleanup: true
    on:
        tags: true
