dist: xenial
addons:
  apt:
    packages:
      - kcov
    sources:
      - sourceline: 'ppa:sivakov512/kcov'

language: rust
rust:
  - stable

env:
  - RUSTFLAGS="-C link-dead-code"

before_cache:
  - find ./target -name "*goto_project-*" -exec rm -rf "{}" \;
  - find ./target -name "gt-*" -exec rm -rf "{}" \;
  - rm -rf ./target/.rustc_info.json
  - cargo clean -p goto-project

cache:
  cargo: true

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - |
    cargo test --verbose --all --no-run &&
    export CARGO_TEST_BIN=`find ./target/debug/ -maxdepth 1 -name "gt-*" -not -name "*.d"` &&
    echo "Compiled binary with tests found at: $CARGO_TEST_BIN" &&
    kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo,/usr/lib,/usr/include target/cov $CARGO_TEST_BIN


before_deploy:
  - RUSTFLAGS="" cargo build --release

deploy:
  - provider: script
    script: RUSTFLAGS="" cargo publish --token $CRATES_TOKEN
    skip_cleanup: true
    on:
        tags: true

  - provider: releases
    api_key: $GITHUB_TOKEN
    file: target/release/gt
    skip_cleanup: true
    on:
        tags: true
